# Numpy

In [2]:
import numpy as np 

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.ndim

1

In [8]:
a.shape

(3,)

## 1.Time Functions

In [4]:
l=range(10)
%timeit [i*2 for i in l]

1.79 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
m=np.arange(10)
%timeit a**2

1.53 µs ± 39.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
b=np.array([[1,2,3],[4,5,6]])   #this is 2d array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b.ndim


2

In [25]:
b.shape

(2, 3)

## 2.Arrays

In [20]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]]) #this is 3d array
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
c.ndim

3

In [27]:
c.shape

(2, 2, 2)

### 3.Functions in Num

In [28]:
d=np.arange(10) #similar to that of range in list
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [31]:
d=np.linspace(0,2)   #this is list of points
d

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

## 4.Random

In [37]:
a=np.random.rand(10)    #ran is loaded from the uniform distribution
a

array([0.45835421, 0.8704178 , 0.26480607, 0.42470964, 0.3063918 ,
       0.27660774, 0.07534779, 0.71796324, 0.23540064, 0.6761233 ])

In [38]:
a=np.random.random(10)   #random is loaded from the standard normal distribution
a

array([0.49043745, 0.83474765, 0.91255263, 0.17192914, 0.36932767,
       0.7150863 , 0.20223142, 0.26392246, 0.01733682, 0.55863777])

## 5.Matrices

In [33]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [5]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 6.Some Datatypes

In [42]:
a=np.arange(10,dtype="float64")
print(a)
print(type(a))
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>
float64


In [43]:
a=np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [46]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [48]:
a=np.array([2+3j])
print(a.dtype)

complex128


## 7.Indexing and Slicing

In [49]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[5]

5

In [52]:
a=np.array([10,20])
a

array([10, 20])

In [53]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [55]:
a[3,1]=5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 5, 0, 4]])

In [57]:
a[3:]=5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [5, 5, 5, 5]])

## 8.ElementWise Operations

In [59]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [69]:
b=np.array([1,2,3,5])
b

array([1, 2, 3, 5])

In [70]:
print(a-b)

[ 0  0  0 -1]


In [71]:
a*b

array([ 1,  4,  9, 20])

In [72]:
a//b

array([1, 1, 1, 0], dtype=int32)

In [76]:
c=np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [79]:
c.dot(c)     #To multiply element to itself

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [80]:
a=np.array([1,2,3,4])
b=np.array([3,4,5,4])
print(a==b)

[False False False  True]


In [83]:
a=np.array([1,0,0,1])
b=np.array([1,1,0,1])
print(np.logical_or(a,b))
print(np.logical_and(a,b))


[ True  True False  True]
[ True False False  True]


## 9.Trig 

In [87]:
a=np.arange(1,5)
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [90]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [92]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## 10.Order

In [94]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [98]:
a.sum(axis=0)

array([4, 6])

In [100]:
a.sum(axis=1)

array([3, 7])

In [6]:
a.argmin()

1

In [7]:
a.argmax()

0

## 11.Other reductions

In [104]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [107]:
print(a.min())
print(a.max())

1
5


In [108]:
print(a.argmin())

0


In [109]:
print(a.argmax())

4


## 12.Statistics

In [110]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [111]:
a.mean()

2.5

In [114]:
np.median(a)

2.5

In [118]:
a.std()

1.118033988749895

## 13.Matrix Manipulations

In [140]:
a=np.array([[1,22,3],[4,5,6]])
a

array([[ 1, 22,  3],
       [ 4,  5,  6]])

In [143]:
a.T

array([[ 1,  4],
       [ 3,  6],
       [ 5, 22]])

In [129]:
b=a.ravel()    #Ravel Function reshapes MultiDim to Single Dim
b

array([1, 2, 3, 4, 5, 6])

In [132]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
a.sort(axis=1)
a

array([[ 1,  3,  5],
       [ 4,  6, 22]])